# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lkRBwK6ePG1+KQQ1agcFk98TLgg8uq9k6ZlGnA8PLDBYEfKGmgdSqD6p5CslIOYTl9R9X8VcTeopEhPKZp9hZG+7J1hflLrjVm90ImIOmOEVDg7DmXnBlqCqMquVht09+in3fpJ9Ra3wjdqCfQdeheIstf5SL2nSW5YhZIg3r87dZapC+YRSGaYogsjAubDqbEIwJODICm0qCLJyL+eBOC1PbRsJsFgp+4vjCiXSTY9JWWbJz6wjWLzEqKXUPRcmTCW4iNXjkj7zL8rKG8cNinoHkyuVr1BjA9Q/ck1lemXKzDyGTmVTTMXSBc4IQKf0NlUgBHjgLFHt1HSdnASHm5kcmuopH+ALC4EaLShBhSNd7ObcwnPqbhPLJXliVmRUVe9vMivZ5JBDWW90Lvm2E601ZjcN64N+RHAfZ79y+1sigQNZOSI+1KJWgPg0h+1x3UdBnK3YsyeV/GyzXuxHh3fpFNhKa55fJHvDy0RyFacWVny8TFG3Za5DZNDUGCXUzyFx5cVfE2vztnBX2NmGHX3+QO98XA9NuPocZ7juIyzClOu+tVf4fd+ezCLhQeL72ur3jdAsCMWgFYziMbHRKV94ou3GnZA9Bwto77+NPjjmwGnXze5ZLaAZYiolxsK1D4gIJ6j7Sy5e241VjAeW2pldsOIWQVW1UUGeEQCO92g="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
